name: Unit-tests

on:
  push:
    branches: [main, develop]

jobs:
  default-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Test Eslint
        run: |
          npm i
          npm run test
